services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP
    networks:
      - mailhog_net

networks:
  mailhog_net:
    external: true
    name: airflow_streaming_default