services:
  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    ports:
      - "8025:80"  # Interface Web
      - "25:25"    # SMTP
    networks:
      - airflow_net

networks:
  airflow_net:
    external: true
    name: airflow_streaming_default